"""add batch_images table

Revision ID: 2f0bdfaaf0bd
Revises: 6cb89125f2f4
Create Date: 2026-07-22 17:09:03.886902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0bdfaaf0bd'
down_revision: Union[str, Sequence[str], None] = '6cb89125f2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False, comment='关联批次'),
    sa.Column('image_path', sa.String(length=500), nullable=False, comment='图片相对路径'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='图片访问URL'),
    sa.Column('filename', sa.String(length=200), nullable=False, comment='原始文件名'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('image_width', sa.Integer(), nullable=True, comment='图片宽度'),
    sa.Column('image_height', sa.Integer(), nullable=True, comment='图片高度'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending/detected/pass/fail'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['pcb_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_images_batch_id'), 'batch_images', ['batch_id'], unique=False)
    op.drop_index('ix_ra_role_id', table_name='role_applications')
    op.drop_index('ix_ra_user_id', table_name='role_applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ra_user_id', 'role_applications', ['user_id'], unique=False)
    op.create_index('ix_ra_role_id', 'role_applications', ['role_id'], unique=False)
    op.drop_index(op.f('ix_batch_images_batch_id'), table_name='batch_images')
    op.drop_table('batch_images')
    # ### end Alembic commands ###
