"""add is_approved column and role_applications table

Revision ID: 6cb89125f2f4
Revises: 2eeb654d84eb
Create Date: 2026-07-20 17:15:13.505341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cb89125f2f4'
down_revision: Union[str, Sequence[str], None] = '2eeb654d84eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='申请人'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='申请的角色'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='申请状态：pending/approved/rejected'),
    sa.Column('approver_id', sa.Integer(), nullable=True, comment='审批人'),
    sa.Column('approve_comment', sa.String(length=500), nullable=True, comment='审批意见'),
    sa.Column('applied_at', sa.DateTime(), nullable=True, comment='申请时间'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_applications_role_id'), 'role_applications', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_applications_user_id'), 'role_applications', ['user_id'], unique=False)
    op.alter_column('detection_tasks', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='任务来源：quick（快捷检测）/batch（批次检测）/manual（手动创建）',
               existing_nullable=True)
    op.alter_column('training_tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'),
               nullable=False,
               comment='任务状态',
               existing_comment='状态: pending/running/completed/failed/cancelled')
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True, comment='是否已审批通过'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    op.alter_column('training_tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'),
               nullable=True,
               comment='状态: pending/running/completed/failed/cancelled',
               existing_comment='任务状态')
    op.alter_column('detection_tasks', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='任务来源：quick（快捷检测）/batch（批次检测）/manual（手动创建）',
               existing_nullable=True)
    op.drop_index(op.f('ix_role_applications_user_id'), table_name='role_applications')
    op.drop_index(op.f('ix_role_applications_role_id'), table_name='role_applications')
    op.drop_table('role_applications')
    # ### end Alembic commands ###
