"""add_source_column_to_detection_tasks

Revision ID: aafa77e21197
Revises: 2eeb654d84eb
Create Date: 2026-07-16 17:21:10.022091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafa77e21197'
down_revision: Union[str, Sequence[str], None] = '2eeb654d84eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detection_tasks', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='任务来源：quick（快捷检测）/batch（批次检测）/manual（手动创建）',
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detection_tasks', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='任务来源：quick（快捷检测）/batch（批次检测）/manual（手动创建）',
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    # ### end Alembic commands ###
