"""init: create users, detection_records, training_tasks 
tables

Revision ID: 2eeb654d84eb
Revises: 
Create Date: 2026-07-09 16:56:55.138918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2eeb654d84eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    taskstatus_enum = postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus')
    taskstatus_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('defect_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='缺陷编码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='缺陷名称'),
    sa.Column('name_cn', sa.String(length=100), nullable=False, comment='中文名称'),
    sa.Column('severity', sa.Enum('MINOR', 'MAJOR', 'CRITICAL', name='defectseverity'), nullable=True, comment='默认严重程度'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='缺陷描述'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('pcb_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False, comment='批次号'),
    sa.Column('pcb_type', sa.String(length=100), nullable=False, comment='PCB型号'),
    sa.Column('production_line', sa.String(length=50), nullable=False, comment='产线编号'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='总数量'),
    sa.Column('inspected_count', sa.Integer(), nullable=True, comment='已检测数量'),
    sa.Column('pass_count', sa.Integer(), nullable=True, comment='良品数量'),
    sa.Column('fail_count', sa.Integer(), nullable=True, comment='不良品数量'),
    sa.Column('pass_rate', sa.Float(), nullable=True, comment='良品率'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending/in_progress/completed'),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcb_batches_batch_no'), 'pcb_batches', ['batch_no'], unique=True)
    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='所属场景'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='数据集版本号，如 v1.0.2'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='数据集名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='版本说明（如新增了氧化缺陷样本）'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='数据集存储相对路径'),
    sa.Column('data_yaml_path', sa.String(length=500), nullable=True, comment='data.yaml 文件路径'),
    sa.Column('image_count', sa.Integer(), nullable=True, comment='图像总数'),
    sa.Column('class_distribution', sa.JSON(), nullable=True, comment='类别分布统计，如 {"short":150, "open":80}'),
    sa.Column('data_hash', sa.String(length=64), nullable=True, comment='数据集校验哈希值（防篡改）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否当前活跃数据集'),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['detection_scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_scene_id'), 'dataset_versions', ['scene_id'], unique=False)
    op.alter_column('detection_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'),
               existing_nullable=True,
               postgresql_using='status::taskstatus') 
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='消息角色：user/assistant/tool/system',
               existing_comment='消息⻆⾊：user/assistant/tool/system',
               existing_nullable=False)
    op.alter_column('chat_messages', 'agent_used',
               existing_type=sa.VARCHAR(length=50),
               comment='处理的 Agent',
               existing_comment='处理的 Agent：supervisor/detection/analysis/qa',
               existing_nullable=True)
    op.alter_column('chat_messages', 'tool_calls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='工具调用记录',
               existing_comment='⼯具调⽤记录，如 [{"tool":"detect_objects","args":{...}}]',
               existing_nullable=True)
    op.alter_column('chat_messages', 'tool_result',
               existing_type=sa.TEXT(),
               comment='工具调用返回结果',
               existing_comment='⼯具调⽤返回结果',
               existing_nullable=True)
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户',
               existing_comment='所属⽤户',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'session_uuid',
               existing_type=sa.VARCHAR(length=100),
               comment='会话唯一标识',
               existing_comment='会话唯⼀标识',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='会话标题',
               existing_comment='会话标题（取第⼀条消息摘要）',
               existing_nullable=True)
    op.drop_constraint(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('detection_results', sa.Column('severity', sa.Enum('MINOR', 'MAJOR', 'CRITICAL', name='defectseverity'), nullable=True, comment='缺陷严重等级'))
    op.add_column('detection_results', sa.Column('repair_suggestion', sa.Text(), nullable=True, comment='针对该缺陷的维修/调整建议'))
    op.add_column('detection_results', sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='复判人'))
    op.add_column('detection_results', sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='复判时间'))
    op.add_column('detection_results', sa.Column('defect_type_id', sa.Integer(), nullable=True, comment='关联缺陷类型'))
    op.alter_column('detection_results', 'task_id',
               existing_type=sa.INTEGER(),
               comment='所属任务',
               existing_comment='所属检测任务',
               existing_nullable=False)
    op.alter_column('detection_results', 'image_path',
               existing_type=sa.VARCHAR(length=500),
               comment='原始图像相对路径（如 scenes/pcb/xxx.jpg）',
               existing_comment='原始图像路径',
               existing_nullable=False)
    op.alter_column('detection_results', 'class_name_cn',
               existing_type=sa.VARCHAR(length=50),
               comment='类别中文名',
               existing_comment='类别中⽂名',
               existing_nullable=True)
    op.alter_column('detection_results', 'image_height',
               existing_type=sa.INTEGER(),
               comment='图像高度',
               existing_comment='图像⾼度',
               existing_nullable=True)
    op.alter_column('detection_results', 'review_status',
               existing_type=postgresql.ENUM('PENDING', 'PASS', 'FAIL', 'REPAIR', name='reviewstatus'),
               comment='复判状态',
               existing_nullable=False)
    op.create_index('idx_result_task_class', 'detection_results', ['task_id', 'class_name'], unique=False)
    op.create_index(op.f('ix_detection_results_defect_type_id'), 'detection_results', ['defect_type_id'], unique=False)
    op.drop_constraint(op.f('detection_results_task_id_fkey'), 'detection_results', type_='foreignkey')
    op.create_foreign_key(None, 'detection_results', 'defect_types', ['defect_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'detection_results', 'detection_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detection_results', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.add_column('detection_scenes', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间'))
    op.alter_column('detection_scenes', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='场景标识',
               existing_comment='场景标识，如 remote_sensing',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='场景显示名',
               existing_comment='场景显示名，如 遥感⽬标检测',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='场景分类',
               existing_comment='场景分类：agriculture/industry/remote_sensing/medical/traffic',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'class_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='类别列表',
               existing_comment='类别列表，如 ["airplane","storage-tank"]',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'class_names_cn',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='类别中文映射',
               existing_comment='类别中⽂名映射，如 {"airplane":"⻜机"}',
               existing_nullable=True)
    op.alter_column('detection_scenes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_comment='是否启⽤',
               existing_nullable=True)
    op.alter_column('detection_scenes', 'created_by',
               existing_type=sa.INTEGER(),
               comment='创建人',
               existing_comment='创建⼈',
               existing_nullable=True)
    op.create_index(op.f('ix_detection_scenes_deleted_at'), 'detection_scenes', ['deleted_at'], unique=False)
    op.add_column('detection_tasks', sa.Column('batch_id', sa.Integer(), nullable=True, comment='关联PCB批次'))
    op.alter_column('detection_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='操作用户',
               existing_comment='操作⽤户')
    op.alter_column('detection_tasks', 'scene_id',
               existing_type=sa.INTEGER(),
               comment='检测场景',
               existing_comment='使⽤的检测场景',
               existing_nullable=False)
    op.alter_column('detection_tasks', 'model_version_id',
               existing_type=sa.INTEGER(),
               comment='使用的模型版本',
               existing_comment='使⽤的模型版本',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'),
               nullable=False,
               comment='任务状态',
               existing_comment='状态：pending/processing/completed/failed')
    op.alter_column('detection_tasks', 'total_objects',
               existing_type=sa.INTEGER(),
               comment='检测到目标总数',
               existing_comment='检测到⽬标总数',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'image_size',
               existing_type=sa.INTEGER(),
               comment='推理图像尺寸',
               existing_comment='推理图像尺⼨',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'analysis_report',
               existing_type=sa.TEXT(),
               comment='分析报告（Markdown）',
               existing_comment='分析报告（Markdown 格式）',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment='风险等级：low/medium/high/critical',
               existing_comment='⻛险等级：low/medium/high/critical',
               existing_nullable=True)
    op.create_index('idx_detection_task_user_status', 'detection_tasks', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_detection_tasks_batch_id'), 'detection_tasks', ['batch_id'], unique=False)
    op.drop_constraint(op.f('detection_tasks_scene_id_fkey'), 'detection_tasks', type_='foreignkey')
    op.drop_constraint(op.f('detection_tasks_model_version_id_fkey'), 'detection_tasks', type_='foreignkey')
    op.drop_constraint(op.f('detection_tasks_user_id_fkey'), 'detection_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'detection_tasks', 'pcb_batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'detection_tasks', 'detection_scenes', ['scene_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'detection_tasks', 'model_versions', ['model_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'detection_tasks', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('model_versions', sa.Column('export_format', sa.String(length=20), nullable=True, comment='导出格式：onnx/trt/pytorch'))
    op.add_column('model_versions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间'))
    op.alter_column('model_versions', 'training_task_id',
               existing_type=sa.INTEGER(),
               comment='来源训练任务',
               existing_comment='来源训练任务（可为空，⽀持⼿动上传）',
               existing_nullable=True)
    op.alter_column('model_versions', 'model_type',
               existing_type=sa.VARCHAR(length=50),
               comment='模型类型',
               existing_comment='模型类型：yolov11n/s/m/l/x',
               existing_nullable=True)
    op.alter_column('model_versions', 'model_path',
               existing_type=sa.VARCHAR(length=500),
               comment='本地模型文件相对路径',
               existing_comment='本地模型⽂件路径',
               existing_nullable=False)
    op.alter_column('model_versions', 'per_class_ap',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='各类别 AP',
               existing_comment='各类别 AP，如 {"airplane":0.85,"tank":0.72}',
               existing_nullable=True)
    op.alter_column('model_versions', 'file_size',
               existing_type=sa.BIGINT(),
               comment='模型文件大小（字节）',
               existing_comment='模型⽂件⼤⼩（字节）',
               existing_nullable=True)
    op.create_index(op.f('ix_model_versions_deleted_at'), 'model_versions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_model_versions_training_task_id'), 'model_versions', ['training_task_id'], unique=False)
    op.drop_constraint(op.f('model_versions_training_task_id_fkey'), 'model_versions', type_='foreignkey')
    op.drop_constraint(op.f('model_versions_scene_id_fkey'), 'model_versions', type_='foreignkey')
    op.create_foreign_key(None, 'model_versions', 'training_tasks', ['training_task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'model_versions', 'detection_scenes', ['scene_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('model_versions', 'box_loss')
    op.drop_column('model_versions', 'dfl_loss')
    op.drop_column('model_versions', 'cls_loss')
    op.drop_column('model_versions', 'lr')
    op.alter_column('operation_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='操作用户',
               existing_comment='操作⽤户（可为空表示系统操作）',
               existing_nullable=True)
    op.alter_column('operation_logs', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='冗余用户名',
               existing_comment='冗余⽤户名，⽅便查询',
               existing_nullable=True)
    op.alter_column('operation_logs', 'module',
               existing_type=sa.VARCHAR(length=50),
               comment='操作模块',
               existing_comment='操作模块：auth/detection/training/agent/system',
               existing_nullable=False)
    op.alter_column('operation_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型',
               existing_comment='操作类型：create/update/delete/login/export',
               existing_nullable=False)
    op.alter_column('operation_logs', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               comment='操作对象类型',
               existing_comment='操作对象类型：user/task/model/session',
               existing_nullable=True)
    op.alter_column('operation_logs', 'request_method',
               existing_type=sa.VARCHAR(length=10),
               comment='HTTP 方法',
               existing_comment='HTTP ⽅法',
               existing_nullable=True)
    op.drop_constraint(op.f('operation_logs_user_id_fkey'), 'operation_logs', type_='foreignkey')
    op.create_foreign_key(None, 'operation_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               comment='权限编码',
               existing_comment='权限编码，如detection:task:create',
               existing_nullable=False)
    op.alter_column('permissions', 'module',
               existing_type=sa.VARCHAR(length=50),
               comment='所属模块',
               existing_comment='所属模块：auth/detection/training/agent/system',
               existing_nullable=False)
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间'))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='角色标识',
               existing_comment='⻆⾊标识，如 admin/operator/viewer',
               existing_nullable=False)
    op.alter_column('roles', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='角色显示名',
               existing_comment='⻆⾊显示名，如 管理员/操作员/访客',
               existing_nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='角色描述',
               existing_comment='⻆⾊描述',
               existing_nullable=True)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='是否系统内置角色（不可删除）',
               existing_comment='是否系统内置⻆⾊（不可删除）',
               existing_nullable=True)
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.alter_column('training_metrics', 'task_id',
               existing_type=sa.INTEGER(),
               comment='所属任务',
               existing_comment='所属训练任务',
               existing_nullable=False)
    op.drop_constraint(op.f('training_metrics_task_id_fkey'), 'training_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'training_metrics', 'training_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.add_column('training_tasks', sa.Column('dataset_version_id', sa.Integer(), nullable=True, comment='使用的数据集版本'))
    op.alter_column('training_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='操作用户')
    op.alter_column('training_tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'),
               existing_nullable=True,
               postgresql_using='status::taskstatus')
    op.alter_column('training_tasks', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               comment='基础模型',
               existing_comment='基础模型: yolov11n/s/m/l/x',
               existing_nullable=True)
    op.alter_column('training_tasks', 'device',
               existing_type=sa.VARCHAR(length=20),
               comment='训练设备',
               existing_comment='训练设备: 0/1/cpu',
               existing_nullable=True)
    op.alter_column('training_tasks', 'optimizer',
               existing_type=sa.VARCHAR(length=20),
               comment='优化器',
               existing_comment='优化器: SGD/Adam/AdamW',
               existing_nullable=True)
    op.alter_column('training_tasks', 'dataset_path',
               existing_type=sa.VARCHAR(length=500),
               comment='数据集路径（兼容旧版，建议使用dataset_version_id）',
               existing_comment='数据集路径',
               existing_nullable=True)
    op.create_index(op.f('ix_training_tasks_dataset_version_id'), 'training_tasks', ['dataset_version_id'], unique=False)
    op.drop_constraint(op.f('training_tasks_user_id_fkey'), 'training_tasks', type_='foreignkey')
    op.drop_constraint(op.f('training_tasks_scene_id_fkey'), 'training_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'training_tasks', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'training_tasks', 'detection_scenes', ['scene_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'training_tasks', 'dataset_versions', ['dataset_version_id'], ['id'], ondelete='SET NULL')
    op.drop_column('training_tasks', 'dataset_size')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='用户名',
               existing_comment='⽤户名',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='手机号',
               existing_comment='⼿机号',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_comment='是否启⽤',
               existing_nullable=True)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启⽤',
               existing_comment='是否启用',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='⼿机号',
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='⽤户名',
               existing_comment='用户名',
               existing_nullable=False)
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'])
    op.add_column('training_tasks', sa.Column('dataset_size', sa.INTEGER(), autoincrement=False, nullable=True, comment='数据集图像数量'))
    op.drop_constraint(None, 'training_tasks', type_='foreignkey')
    op.drop_constraint(None, 'training_tasks', type_='foreignkey')
    op.drop_constraint(None, 'training_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('training_tasks_scene_id_fkey'), 'training_tasks', 'detection_scenes', ['scene_id'], ['id'])
    op.create_foreign_key(op.f('training_tasks_user_id_fkey'), 'training_tasks', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_training_tasks_dataset_version_id'), table_name='training_tasks')
    op.alter_column('training_tasks', 'dataset_path',
               existing_type=sa.VARCHAR(length=500),
               comment='数据集路径',
               existing_comment='数据集路径（兼容旧版，建议使用dataset_version_id）',
               existing_nullable=True)
    op.alter_column('training_tasks', 'optimizer',
               existing_type=sa.VARCHAR(length=20),
               comment='优化器: SGD/Adam/AdamW',
               existing_comment='优化器',
               existing_nullable=True)
    op.alter_column('training_tasks', 'device',
               existing_type=sa.VARCHAR(length=20),
               comment='训练设备: 0/1/cpu',
               existing_comment='训练设备',
               existing_nullable=True)
    op.alter_column('training_tasks', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               comment='基础模型: yolov11n/s/m/l/x',
               existing_comment='基础模型',
               existing_nullable=True)
    op.alter_column('training_tasks', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='状态: pending/running/completed/failed/cancelled',
               existing_comment='任务状态')
    op.alter_column('training_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='操作用户')
    op.drop_column('training_tasks', 'dataset_version_id')
    op.drop_constraint(None, 'training_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('training_metrics_task_id_fkey'), 'training_metrics', 'training_tasks', ['task_id'], ['id'])
    op.alter_column('training_metrics', 'task_id',
               existing_type=sa.INTEGER(),
               comment='所属训练任务',
               existing_comment='所属任务',
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='是否系统内置⻆⾊（不可删除）',
               existing_comment='是否系统内置角色（不可删除）',
               existing_nullable=True)
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='⻆⾊描述',
               existing_comment='角色描述',
               existing_nullable=True)
    op.alter_column('roles', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='⻆⾊显示名，如 管理员/操作员/访客',
               existing_comment='角色显示名',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='⻆⾊标识，如 admin/operator/viewer',
               existing_comment='角色标识',
               existing_nullable=False)
    op.drop_column('roles', 'deleted_at')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.alter_column('permissions', 'module',
               existing_type=sa.VARCHAR(length=50),
               comment='所属模块：auth/detection/training/agent/system',
               existing_comment='所属模块',
               existing_nullable=False)
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               comment='权限编码，如detection:task:create',
               existing_comment='权限编码',
               existing_nullable=False)
    op.drop_constraint(None, 'operation_logs', type_='foreignkey')
    op.create_foreign_key(op.f('operation_logs_user_id_fkey'), 'operation_logs', 'users', ['user_id'], ['id'])
    op.alter_column('operation_logs', 'request_method',
               existing_type=sa.VARCHAR(length=10),
               comment='HTTP ⽅法',
               existing_comment='HTTP 方法',
               existing_nullable=True)
    op.alter_column('operation_logs', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               comment='操作对象类型：user/task/model/session',
               existing_comment='操作对象类型',
               existing_nullable=True)
    op.alter_column('operation_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型：create/update/delete/login/export',
               existing_comment='操作类型',
               existing_nullable=False)
    op.alter_column('operation_logs', 'module',
               existing_type=sa.VARCHAR(length=50),
               comment='操作模块：auth/detection/training/agent/system',
               existing_comment='操作模块',
               existing_nullable=False)
    op.alter_column('operation_logs', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='冗余⽤户名，⽅便查询',
               existing_comment='冗余用户名',
               existing_nullable=True)
    op.alter_column('operation_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='操作⽤户（可为空表示系统操作）',
               existing_comment='操作用户',
               existing_nullable=True)
    op.add_column('model_versions', sa.Column('lr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='当前学习率'))
    op.add_column('model_versions', sa.Column('cls_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='分类损失'))
    op.add_column('model_versions', sa.Column('dfl_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='DFL 损失'))
    op.add_column('model_versions', sa.Column('box_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='边界框损失'))
    op.drop_constraint(None, 'model_versions', type_='foreignkey')
    op.drop_constraint(None, 'model_versions', type_='foreignkey')
    op.create_foreign_key(op.f('model_versions_scene_id_fkey'), 'model_versions', 'detection_scenes', ['scene_id'], ['id'])
    op.create_foreign_key(op.f('model_versions_training_task_id_fkey'), 'model_versions', 'training_tasks', ['training_task_id'], ['id'])
    op.drop_index(op.f('ix_model_versions_training_task_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_deleted_at'), table_name='model_versions')
    op.alter_column('model_versions', 'file_size',
               existing_type=sa.BIGINT(),
               comment='模型⽂件⼤⼩（字节）',
               existing_comment='模型文件大小（字节）',
               existing_nullable=True)
    op.alter_column('model_versions', 'per_class_ap',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='各类别 AP，如 {"airplane":0.85,"tank":0.72}',
               existing_comment='各类别 AP',
               existing_nullable=True)
    op.alter_column('model_versions', 'model_path',
               existing_type=sa.VARCHAR(length=500),
               comment='本地模型⽂件路径',
               existing_comment='本地模型文件相对路径',
               existing_nullable=False)
    op.alter_column('model_versions', 'model_type',
               existing_type=sa.VARCHAR(length=50),
               comment='模型类型：yolov11n/s/m/l/x',
               existing_comment='模型类型',
               existing_nullable=True)
    op.alter_column('model_versions', 'training_task_id',
               existing_type=sa.INTEGER(),
               comment='来源训练任务（可为空，⽀持⼿动上传）',
               existing_comment='来源训练任务',
               existing_nullable=True)
    op.drop_column('model_versions', 'deleted_at')
    op.drop_column('model_versions', 'export_format')
    op.drop_constraint(None, 'detection_tasks', type_='foreignkey')
    op.drop_constraint(None, 'detection_tasks', type_='foreignkey')
    op.drop_constraint(None, 'detection_tasks', type_='foreignkey')
    op.drop_constraint(None, 'detection_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('detection_tasks_user_id_fkey'), 'detection_tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('detection_tasks_model_version_id_fkey'), 'detection_tasks', 'model_versions', ['model_version_id'], ['id'])
    op.create_foreign_key(op.f('detection_tasks_scene_id_fkey'), 'detection_tasks', 'detection_scenes', ['scene_id'], ['id'])
    op.drop_index(op.f('ix_detection_tasks_batch_id'), table_name='detection_tasks')
    op.drop_index('idx_detection_task_user_status', table_name='detection_tasks')
    op.alter_column('detection_tasks', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment='⻛险等级：low/medium/high/critical',
               existing_comment='风险等级：low/medium/high/critical',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'analysis_report',
               existing_type=sa.TEXT(),
               comment='分析报告（Markdown 格式）',
               existing_comment='分析报告（Markdown）',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'image_size',
               existing_type=sa.INTEGER(),
               comment='推理图像尺⼨',
               existing_comment='推理图像尺寸',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'total_objects',
               existing_type=sa.INTEGER(),
               comment='检测到⽬标总数',
               existing_comment='检测到目标总数',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='状态：pending/processing/completed/failed',
               existing_comment='任务状态')
    op.alter_column('detection_tasks', 'model_version_id',
               existing_type=sa.INTEGER(),
               comment='使⽤的模型版本',
               existing_comment='使用的模型版本',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'scene_id',
               existing_type=sa.INTEGER(),
               comment='使⽤的检测场景',
               existing_comment='检测场景',
               existing_nullable=False)
    op.alter_column('detection_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='操作⽤户',
               existing_comment='操作用户')
    op.drop_column('detection_tasks', 'batch_id')
    op.drop_index(op.f('ix_detection_scenes_deleted_at'), table_name='detection_scenes')
    op.alter_column('detection_scenes', 'created_by',
               existing_type=sa.INTEGER(),
               comment='创建⼈',
               existing_comment='创建人',
               existing_nullable=True)
    op.alter_column('detection_scenes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启⽤',
               existing_comment='是否启用',
               existing_nullable=True)
    op.alter_column('detection_scenes', 'class_names_cn',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='类别中⽂名映射，如 {"airplane":"⻜机"}',
               existing_comment='类别中文映射',
               existing_nullable=True)
    op.alter_column('detection_scenes', 'class_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='类别列表，如 ["airplane","storage-tank"]',
               existing_comment='类别列表',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='场景分类：agriculture/industry/remote_sensing/medical/traffic',
               existing_comment='场景分类',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='场景显示名，如 遥感⽬标检测',
               existing_comment='场景显示名',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='场景标识，如 remote_sensing',
               existing_comment='场景标识',
               existing_nullable=False)
    op.drop_column('detection_scenes', 'deleted_at')
    op.drop_constraint(None, 'detection_results', type_='foreignkey')
    op.drop_constraint(None, 'detection_results', type_='foreignkey')
    op.drop_constraint(None, 'detection_results', type_='foreignkey')
    op.create_foreign_key(op.f('detection_results_task_id_fkey'), 'detection_results', 'detection_tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_detection_results_defect_type_id'), table_name='detection_results')
    op.drop_index('idx_result_task_class', table_name='detection_results')
    op.alter_column('detection_results', 'review_status',
               existing_type=postgresql.ENUM('PENDING', 'PASS', 'FAIL', 'REPAIR', name='reviewstatus'),
               comment=None,
               existing_comment='复判状态',
               existing_nullable=False)
    op.alter_column('detection_results', 'image_height',
               existing_type=sa.INTEGER(),
               comment='图像⾼度',
               existing_comment='图像高度',
               existing_nullable=True)
    op.alter_column('detection_results', 'class_name_cn',
               existing_type=sa.VARCHAR(length=50),
               comment='类别中⽂名',
               existing_comment='类别中文名',
               existing_nullable=True)
    op.alter_column('detection_results', 'image_path',
               existing_type=sa.VARCHAR(length=500),
               comment='原始图像路径',
               existing_comment='原始图像相对路径（如 scenes/pcb/xxx.jpg）',
               existing_nullable=False)
    op.alter_column('detection_results', 'task_id',
               existing_type=sa.INTEGER(),
               comment='所属检测任务',
               existing_comment='所属任务',
               existing_nullable=False)
    op.drop_column('detection_results', 'defect_type_id')
    op.drop_column('detection_results', 'reviewed_at')
    op.drop_column('detection_results', 'reviewer_id')
    op.drop_column('detection_results', 'repair_suggestion')
    op.drop_column('detection_results', 'severity')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='会话标题（取第⼀条消息摘要）',
               existing_comment='会话标题',
               existing_nullable=True)
    op.alter_column('chat_sessions', 'session_uuid',
               existing_type=sa.VARCHAR(length=100),
               comment='会话唯⼀标识',
               existing_comment='会话唯一标识',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属⽤户',
               existing_comment='所属用户',
               existing_nullable=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.alter_column('chat_messages', 'tool_result',
               existing_type=sa.TEXT(),
               comment='⼯具调⽤返回结果',
               existing_comment='工具调用返回结果',
               existing_nullable=True)
    op.alter_column('chat_messages', 'tool_calls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='⼯具调⽤记录，如 [{"tool":"detect_objects","args":{...}}]',
               existing_comment='工具调用记录',
               existing_nullable=True)
    op.alter_column('chat_messages', 'agent_used',
               existing_type=sa.VARCHAR(length=50),
               comment='处理的 Agent：supervisor/detection/analysis/qa',
               existing_comment='处理的 Agent',
               existing_nullable=True)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='消息⻆⾊：user/assistant/tool/system',
               existing_comment='消息角色：user/assistant/tool/system',
               existing_nullable=False)
    op.drop_index(op.f('ix_dataset_versions_scene_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_pcb_batches_batch_no'), table_name='pcb_batches')
    op.drop_table('pcb_batches')
    op.drop_table('defect_types')
    # ### end Alembic commands ###
